Map<String, String> arLang = {
  "invoice_amount": "مبلغ الفاتورة",
  "currency_unit": "الوحدة المالية",
  "promotion_groups": "مجموعات العروض الترويجية",
  "payment_method": "طريقة الدفع",
  "store": "المخزن",
  "store_groups": "مجموعات المخازن",
  "store_region_number": "رقم المنطقة المخزن",
  "customer_type": "نوع العميل",
  "customer_group": "مجموعة العملاء",
  "customer_degree": "درجة العميل",
  "customer_activity": "نشاط العميل",
  "customer_classification": "تصنيف العميل",
  "customer_number": "رقم العميل",
  "my_customers": "عملاء نقاطي",
  "available_data": "البيانات المتاحة",
  "selected_data": "البيانات المختارة",
  "exit": "خروج",
  "execute": "تنفيذ",
  "delete_all": "حذف الكل",
  "search_in_detailed_data": "بحث في البيانات التفصيلية",
  "add_all": "إضافة الكل",
  "from_main_group": "من المجموعة الرئيسية",
  "to_group_3": "الى المجموعة 3",
  "from_sub_group": "من المجموعة الفرعية",
  "to_sub_group": "الى المجموعة الفرعية",
  "from_sub_sub_group": "من المجموعة تحت الفرعية",
  "to_sub_sub_group": "الى المجموعة تحت الفرعية",
  "from_detailed_group": "من المجموعة التفصيلية",
  "to_detailed_group": "الى المجموعة التفصيلية",
  "from_item_type": "من نوع الصنف",
  "to_item_type": "الى نوع الصنف",
  "from_item_structure": "من هيكل الصنف",
  "to_item_structure": "الى هيكل الصنف",
  "from_item_activity": "من نشاط الصنف",
  "to_item_activity": "الى نشاط الصنف",
  "from_item_number": "من رقم الصنف",
  "to_item_number": "الى رقم الصنف",
  "from_warehouse": "من مخزن",
  "to_warehouse": "الى مخزن",
  "show_items_with_available_quantities": "عرض الاصناف ذات الكميات المتوفرة",
  "show_quota_items": "عرض أصناف الكوتا",
  "minimum_amount": "الحد الأدنى للمبلغ",
  "discount_amount": "قيمة الخصم",
  "maximum_amount": "الحد الأقصى للمبلغ",
  "discount_type": "نوع الخصم",
  "maximum_number_to_get_this_offer": "الحد الأقصى للحصول على هذا العرض",
  "maximum_quantity_for_offer": "الحد الأقصى للكمية للحصول على العرض",
  "egypt_bank": "بنك مصر",
};
