Map<String, String> enLang = {
  //header
  "invoice_amount": "Invoice Amount",
  "currency_unit": "Currency Unit",
  "promotion_groups": "Promotion Groups",
  "payment_method": "Payment Method",
  "store": "Store",
  "store_groups": "Store Groups",
  "store_region_number": "Store Region Number",
  "customer_type": "Customer Type",
  "customer_group": "Customer Group",
  "customer_degree": "Customer Degree",
  "customer_activity": "Customer Activity",
  "customer_classification": "Customer Classification",
  "customer_number": "Customer Number",
  "my_customers": "My Customers",
  "available_data": "Available Data",
  "selected_data": "Selected Data",
  "exit": "Exit",
  "execute": "Execute",
  "delete_all": "Delete All",
  "search_in_detailed_data": "Search in detailed data",
  "add_all": "Add All",
  "from_main_group": "From the main group",
  "to_group_3": "To group 3",
  "from_sub_group": "From the sub-group",
  "to_sub_group": "To the sub-group",
  "from_sub_sub_group": "From the sub-sub-group",
  "to_sub_sub_group": "To the sub-sub-group",
  "from_detailed_group": "From the detailed group",
  "to_detailed_group": "To the detailed group",
  "from_item_type": "From item type",
  "to_item_type": "To item type",
  "from_item_structure": "From item structure",
  "to_item_structure": "To item structure",
  "from_item_activity": "From item activity",
  "to_item_activity": "To item activity",
  "from_item_number": "From item number",
  "to_item_number": "To item number",
  "from_warehouse": "From warehouse",
  "to_warehouse": "To warehouse",
  "show_items_with_available_quantities":
      "Show items with available quantities",
  "show_quota_items": "Show quota items",

  "minimum_amount": "Minimum Amount",
  "discount_amount": "Discount Amount",
  "maximum_amount": "Maximum Amount",
  "discount_type": "Discount Type",
  "maximum_number_to_get_this_offer": "Maximum Number to get this offer",
  "maximum_quantity_for_offer": "Maximum Quantity for Offer",
  "egypt_bank": "Egypt Bank",
};
